version: '3.7'

services:
  web:
    build: .
    command: python brevet/manage.py runserver 0.0.0.0:8000
    volumes:
      - /brevet/:/usr/src/brevet
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@$$24Fgk.9#
      - POSTGRES_DB=brevet

volumes:
  postgres_data:
