version: '3.7'

services:
  web-blue:
    build: .
    command: sh -c "
      cd /home/brevet/web/brevet
      && python manage.py migrate
      && python manage.py createcachetable
      && python manage.py collectstatic --noinput
      && gunicorn brevet.wsgi --bind 0.0.0.0:8000"
    volumes:
      - media:/home/brevet/web/brevet/media
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped

  web-green:
    build: .
    command: sh -c "
      cd /home/brevet/web/brevet
      && python manage.py migrate
      && python manage.py createcachetable
      && python manage.py collectstatic --noinput
      && gunicorn brevet.wsgi --bind 0.0.0.0:8000"
    volumes:
      - media:/home/brevet/web/brevet/media
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    restart: unless-stopped

  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10
    restart: unless-stopped


  nginx:
    build: ./nginx
    volumes:
      - media:/home/brevet/web/brevet/media
    ports:
      - 1337:80
    restart: unless-stopped

volumes:
  postgres_data:
  media:
