# Generated by Django 5.1.4 on 2025-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0021_alter_personalstatschart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Регистрация закрыта'),
        ),
    ]
