# Generated by Django 5.1.4 on 2025-11-29 19:22

from django.db import migrations


def fn(apps, schema_editor):
    Randonneur = apps.get_model('brevet_database.Randonneur')
    Result = apps.get_model('brevet_database.Result')

    def get_friend_scores(result):
        results = Result.objects.filter(event=result.event).exclude(id=result.id)
        scores = {}
        for other in results:
            score = calc_friend_score(result, other)
            if score:
                scores[other.randonneur_id] = score
        return scores

    def calc_friend_score(result, other):
        if result.id == other.id:
            return 0
        
        if result.event != other.event:
            return 0

        a, b = min(result.time, other.time).total_seconds(), max(result.time, other.time).total_seconds()
        delta = b - a
        max_delta = min(2 * 3600, 0.05 * b) # seconds

        if delta < max_delta:
            return round(100 * (max_delta - delta) / max_delta)
        return 0

    def get_active_years(randonneur):
        q = Result.objects.filter(event__finished=True, randonneur=randonneur)
        dates = q.dates('event__date', 'year')
        years = sorted([x.year for x in dates])
        return years

    def update_friends(randonneur):
        for year in get_active_years(randonneur):       
            min_friends_score = 120

            results = Result.objects.filter(randonneur=randonneur, event__date__year=year)
            scores = {}
            for result in results:
                for key, value in get_friend_scores(result).items():
                    scores[key] = scores.get(key, [])
                    scores[key].append(value)

            for key, value in scores.items():
                if sum(value) >= min_friends_score:
                    friend = Randonneur.objects.get(pk=key)
                    randonneur.friends.add(friend)
                    print(F"{randonneur.russian_surname} {randonneur.russian_name} and {friend.russian_surname} {friend.russian_name} are friends!")

    for randonneur in Randonneur.objects.all():
        update_friends(randonneur)

def reverse_fn(apps, schema_editor):
    Randonneur = apps.get_model('brevet_database.Randonneur')
    for randonneur in Randonneur.objects.all():
        randonneur.friends.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('brevet_database', '0023_randonneur_friends_alter_result_time'),
    ]

    operations = [
        migrations.RunPython(fn, reverse_fn),
    ]
